repos:
- hooks:
  - id: commitizen
    stages: [commit-msg]
    additional_dependencies: ["cz-conventional-gitmoji"]
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.4.1
