---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        additional_dependencies: ["cz-conventional-gitmoji"]
      - id: commitizen-branch
        additional_dependencies: ["cz-conventional-gitmoji"]
        stages: [pre-push]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        stages: [pre-push]
